openapi: 3.0.0
info:
  title: Send Quote Consultation Message
  version: v3.0

paths:
  /oa/message/cs:
    post:
      summary: Send a consultation message
      operationId: SendQuoteConsultationMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                recipient:
                  type: object
                  required: ["user_id"]
                  properties:
                    user_id:
                      type: string
                      description: "ID of the recipient (received via the User detail retrieval API, User list retrieval API)"
                message:
                  type: object
                  required: ["text", "quote_message_id"]
                  properties:
                    text:
                      type: string
                      description: "The text content to send (max limit is 2,000 characters)"
                    quote_message_id:
                      type: string
                      description: Message_id of the message to reply to
            example:
              recipient:
                user_id: "186729651760683225"
              message:
                text: "Chào bạn, Shop có địa chỉ là 182 Lê Đại Hành, P15, Q10, HCM"
                quote_message_id: "48687128d04c9410cd5f"
      responses:
        200:
          description: Message sent successfully
          content:
            text/json:
              schema:
                  type: object
                  required: ["data", "error", "message"]
                  properties:
                    data:
                      type: object
                      required: ["message_id", "user_id"]
                      properties:
                        message_id:
                          type: string
                          description: ID of the message.
                        user_id:
                          type: string
                          description: ID of the recipient.
                        quota:
                          type: object
                          properties:
                            quota_type:
                              type: string
                              description: 'The quota source used (Values: “reply”, "sub_quota", "purchase_quota", "reward_quota").'
                            owner_type:
                              type: string
                              description: 'The entity that owns the Quota Package (Values: OA: The entity is OA, App: The entity is App)'
                            owner_id:
                              type: string
                              description: "The ID of the entity that owns the Quota Package (Values: OA ID or App ID)."
                            remain:
                              type: string
                              description: "The remaining free Consultation messages under the limit of 8 messages 48 hours or under the OA service package limit."
                            total:
                              type: string
                              description: "The total number of Free Consultation messages under the limit of 8 messages 48 hours or under the OA service package limit."
                            expired_date:
                              type: string
                              description: "The expiration date of the Free Consultation messages under the OA service package."
                    error:
                      type: integer
                      description: Error code.
                    message:
                      type: string
                      description: Message status.
              example:
                data:
                  message_id: "63ecf43f0df7dba892e6"
                  user_id: "2512523625412515"
                  quota:
                    quota_type: "reply"
                    remain: "7"
                    total: "8"
                error: 0
                message: "Success"
      security:
        - AccessTokenAuth: []
