openapi: 3.0.0
info:
  version: 3.0.0
  title: Zalo Group Conversation API
paths:
  /v3.0/oa/group/conversation:
    get:
      summary: Retrieve group conversation information
      operationId: getGroupConversation
      parameters:
        - name: group_id
          in: query
          description: The ID of the group to query.
          required: true
          schema:
            type: string
        - name: offset
          in: query
          description: "The offset to query. Default: 0"
          required: false
          schema:
            type: integer
        - name: count
          in: query
          description: "The number of results to query. Default: 5"
          required: false
          schema:
            type: integer
        - name: access_token
          in: header
          description: The access token that allows the application to call the OA API.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A list of group conversation information
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        src:
                          type: integer
                          description: "The message was sent from the OA or user. 0: message from OA, 1: message from user"
                        time:
                          type: integer
                          description: The time the message was sent (timestamp format)
                        type:
                          type: string
                          description: The type of the message.
                        message:
                          type: string
                          description: The content of the message.
                        message_id:
                          type: string
                          description: The ID of the message.
                        from_id:
                          type: string
                          description: The ID of the message sender (user_id or oa_id)
                        from_display_name:
                          type: string
                          description: The display name of the message sender.
                        from_avatar:
                          type: string
                          description: The avatar URL of the message sender.
                        group_id:
                          type: string
                          description: The ID of the group.
                  error:
                    type: integer
                  message:
                    type: string
