openapi: 3.0.0
info:
  title: Invite Interested People to Group API
  version: "1.0"
servers:
  - url: https://openapi.zalo.me
paths:
  /v3.0/oa/group/invite:
    post:
      summary: Invite Interested People to Group
      description: Used to invite people in a group, the app needs to be granted group information management.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - group_id
                - member_user_ids
              properties:
                group_id:
                  type: string
                  description: ID of the group
                member_user_ids:
                  type: array
                  description: List of user ids to invite to join the group
                  items:
                    type: string
            example:
              group_id: "f414c8f76fa586fbdfb4"
              member_user_ids:
                - "8756287263669629130"
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: integer
                    example: 0
                  message:
                    type: string
                    example: "Success"
      parameters:
        - name: access_token
          in: header
          required: true
          description: The token that allows the app to represent OA call the API. See details on how to get access token.
          schema:
            type: string
          example: "<your_access_token>"
